In [2]:
import numpy as np

In [3]:
one = np.array([1,2,3])

In [4]:
one

array([1, 2, 3])

In [5]:
two = np.array([[1,2,3],[2,4,7],[3,5,9]])

In [6]:
two

array([[1, 2, 3],
       [2, 4, 7],
       [3, 5, 9]])

In [7]:
three = np.zeros(4)

In [8]:
three

array([0., 0., 0., 0.])

In [9]:
four = np.ones((3,4,5))

In [10]:
four

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [11]:
five = np.ones((3,5))

In [12]:
five

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
six = np.full((2,3),9)

In [14]:
six

array([[9, 9, 9],
       [9, 9, 9]])

In [15]:
seven = np.arange(8)

In [16]:
seven

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
eight = np.arange(2,10)

In [18]:
eight

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nine = np.arange(5,50,5)

In [20]:
nine

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
ten = np.empty((2,4))

In [22]:
ten

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
eleven = np.empty(10)

In [24]:
eleven

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.29061821e-306,
       9.34609790e-307, 1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
       6.23057349e-307, 1.42419530e-306])

In [25]:
twelve = np.empty_like(one)

In [26]:
twelve

array([       450971566190,        433791697006, 7236828442695525217])

In [27]:
thirteen = np.copy(two)

In [28]:
thirteen

array([[1, 2, 3],
       [2, 4, 7],
       [3, 5, 9]])

In [36]:
fourteen = np.linspace(0,20,10)

In [37]:
fourteen

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])