In [1]:
import numpy as np

In [2]:
arr1 = ([[1,2,4],[69,31,2]])

In [3]:
arr2 = ([[9,7,5],[3,1,9]])

In [4]:
res = np.add(arr1,arr2)

In [5]:
res

array([[10,  9,  9],
       [72, 32, 11]])

In [6]:
resul = np.multiply(arr1,arr2)

In [7]:
resul

array([[  9,  14,  20],
       [207,  31,  18]])

In [8]:
result = np.divide(arr1,arr2)

In [9]:
result

array([[ 0.11111111,  0.28571429,  0.8       ],
       [23.        , 31.        ,  0.22222222]])

In [13]:
r1 = np.array([[10,20],[30,40]])

In [14]:
r2 =np.array([10,20])

In [15]:
r = r1+r2

In [16]:
r

array([[20, 40],
       [40, 60]])

# Basic Aggregation

In [19]:
arr = np.array([1,2,34,3,22,56,7])

In [20]:
t = arr.sum()

In [21]:
t

np.int64(125)

In [22]:
avg = arr.mean()

In [23]:
avg

np.float64(17.857142857142858)

In [24]:
st = arr.std()

In [25]:
st

np.float64(19.297879760878036)

In [26]:
m = arr.max()

In [27]:
m

np.int64(56)

In [28]:
n = arr.min()

In [29]:
n

np.int64(1)

In [30]:
product = arr.prod()

In [31]:
product

np.int64(1759296)

In [32]:
cum = arr.cumsum()

In [33]:
cum

array([  1,   3,  37,  40,  62, 118, 125])

In [34]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
c = a.sum(axis = 1)

In [36]:
c

array([ 6, 15, 24])