In [1]:
import numpy as np

In [2]:
arr1 = np.array([12,13,14])

In [3]:
arr2 = np.array([12,13,14])

In [4]:
res = np.concatenate([arr1,arr2])

In [5]:
res

array([12, 13, 14, 12, 13, 14])

In [6]:
arr_two = np.array([[10,20],[40,50]])

In [7]:
arr_two1 = np.array([[11,21],[41,51]])

In [8]:
result = np.concatenate((arr_two,arr_two1),axis = 0)

In [9]:
result

array([[10, 20],
       [40, 50],
       [11, 21],
       [41, 51]])

In [10]:
result2 = np.concatenate((arr_two,arr_two1),axis = 1)

In [11]:
result2

array([[10, 20, 11, 21],
       [40, 50, 41, 51]])

In [12]:
a = np.array([1,2,3])

In [13]:
b = np.array([7,8,9])

In [14]:
c = np.hstack((a,b))

In [15]:
c

array([1, 2, 3, 7, 8, 9])

In [16]:
d = np.vstack((a,b))

In [17]:
d

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
a2d = np.array([[4,5,6],[9,8,7]])

In [19]:
b2d = np.array([[1,2,3],[11,12,13]])

In [20]:
c2d = np.hstack((a2d,b2d))

In [21]:
c2d

array([[ 4,  5,  6,  1,  2,  3],
       [ 9,  8,  7, 11, 12, 13]])

In [22]:
d2d = np.vstack((a2d,b2d))

In [23]:
d2d

array([[ 4,  5,  6],
       [ 9,  8,  7],
       [ 1,  2,  3],
       [11, 12, 13]])

In [24]:
name = np.array(["Alice","Bob","Charlie"])

In [25]:
score = np.array([70,80,90])