In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)


In [3]:
arr1 = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[arr>5] = 0

In [6]:
arr

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])

In [7]:
mask = (arr1>2) & (arr1<8)

In [8]:
mask

array([False, False,  True,  True,  True,  True,  True, False, False,
       False])

In [9]:
selected = arr[mask]

In [10]:
selected

array([3, 4, 5, 0, 0])

In [11]:
w = np.where( arr1>5 ,"big","small")

In [12]:
w

array(['small', 'small', 'small', 'small', 'small', 'big', 'big', 'big',
       'big', 'big'], dtype='<U5')

# Broadcasting

In [13]:
a = np.array([[1,2,3],[6,7,8]])

In [14]:
a5 = a +5

In [15]:
a5

array([[ 6,  7,  8],
       [11, 12, 13]])

In [16]:
row = np.array([10,20,30])

In [17]:
res = a + row

In [18]:
res

array([[11, 22, 33],
       [16, 27, 38]])