In [1]:
import numpy as np

In [2]:
a1 = np.array([10,20,30,40,50,60,70,80])

In [3]:
a1[5]

np.int64(60)

In [4]:
a1[-3]

np.int64(60)

In [5]:
a1[-1]

np.int64(80)

In [6]:
a2 = np.array([[1,5,7],[6,7,8],[9,2,3]])

In [7]:
a2

array([[1, 5, 7],
       [6, 7, 8],
       [9, 2, 3]])

In [8]:
a2[1,2]

np.int64(8)

In [9]:
a2[2,0]

np.int64(9)

In [10]:
a3 = np.array([1,2,3,4,5,6,7])

In [11]:
a3[2:6]

array([3, 4, 5, 6])

In [12]:
a3[1:]

array([2, 3, 4, 5, 6, 7])

In [13]:
a3[:4]

array([1, 2, 3, 4])

In [14]:
a3[-5:-1]

array([3, 4, 5, 6])

In [15]:
a2[0:2,1:2]

array([[5],
       [7]])

In [17]:
a2[0:2,0:2]

array([[1, 5],
       [6, 7]])

In [18]:
b = a2>4

In [19]:
b

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [20]:
a2[b]

array([5, 7, 6, 7, 8, 9])