In [2]:
import numpy as np

In [3]:
arr = np.arange(45)

In [4]:
arr.reshape(3,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [5]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arr2.sum(axis=0)

array([12, 15, 18])

In [8]:
arr2.sum(axis=1)

array([ 6, 15, 24])

In [9]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
for i in arr2.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [11]:
arr3 = np.array([[2,4,6],[1,8,5]])

In [12]:
arr3.argmin()

np.int64(3)

In [13]:
arr3.argmax()

np.int64(4)

In [14]:
arr3.argsort()

array([[0, 1, 2],
       [0, 2, 1]])