In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
np.split(arr,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [7]:
np.split(arr,[3,7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

In [8]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.split(arr2,3,axis= 0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [11]:
np.split(arr2,3,axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [12]:
np.split(arr2,[1],axis = 1)

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [13]:
np.hsplit(arr2,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [14]:
np.hsplit(arr2,[2])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [15]:
np.vsplit(arr2,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [16]:
np.vsplit(arr2,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]