In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,34,3,22,56,7])

In [3]:
aexp = np.exp(arr)

In [4]:
aexp

array([2.71828183e+00, 7.38905610e+00, 5.83461743e+14, 2.00855369e+01,
       3.58491285e+09, 2.09165950e+24, 1.09663316e+03])

In [5]:
alog = np.log(arr)

In [6]:
alog

array([0.        , 0.69314718, 3.52636052, 1.09861229, 3.09104245,
       4.02535169, 1.94591015])

In [7]:
total = np.sum(arr)

In [9]:
total

np.int64(125)

In [10]:
s = np.sqrt(arr)

In [11]:
s

array([1.        , 1.41421356, 5.83095189, 1.73205081, 4.69041576,
       7.48331477, 2.64575131])

In [12]:
pwr = np.power(arr,3)

In [13]:
pwr

array([     1,      8,  39304,     27,  10648, 175616,    343])

In [14]:
rec = np.reciprocal(arr)

In [15]:
rec

array([1, 0, 0, 0, 0, 0, 0])

In [16]:
sine = np.sin(arr)

In [17]:
sine

array([ 0.84147098,  0.90929743,  0.52908269,  0.14112001, -0.00885131,
       -0.521551  ,  0.6569866 ])

In [18]:
ab = np.abs(arr)

In [19]:
ab

array([ 1,  2, 34,  3, 22, 56,  7])

In [20]:
cosecant = np.cos(arr)

In [21]:
cosecant

array([ 0.54030231, -0.41614684, -0.84857027, -0.9899925 , -0.99996083,
        0.85322011,  0.75390225])